# Generated by Django 6.0.2 on 2026-02-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sol', models.IntegerField()),
                ('temp', models.FloatField()),
                ('hum', models.FloatField()),
                ('lumière', models.IntegerField()),
                ('periode', models.CharField(max_length=10)),
                ('servo', models.IntegerField()),
                ('pompe', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
